[project]
name = "false-negative-optimization-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib==1.3.2",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "scikit-learn==1.4.2",
]
